version: '3.3'

services:
  redis:
    image: redislabs/redismod
    restart: on-failure
    ports:
      - 6379:6379
    healthcheck:
      test: redis-cli ping
      interval: 30s
      timeout: 10s
      retries: 3

  bot:
    build: ./src
    restart: on-failure
    environment:
      - TOKEN=${JOEBIDEN}
      - REDIS_URL=redis://redis:6379/