name: Deploy app

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_LOGIN }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push
        id: build-image
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          docker \
            --build-arg TOKEN=$TOKEN
            build ./src/ -f /src/Dockerfile -t m2n2/joebiden:latest
          docker push m2n2/joebiden:latest
